export enum RoutePaths{
    DASHBOARD='dashboard',
    HOME='home',
    LOGIN='login',
    REGISTER='register',
    UNIVERSITE='universite',
    CHAMBRE='chambre',
    RESERVATION='reservation',
    GESTION='gestion',
    USER='utilisateur',
    ETUDIANT='etudiant',
    PASSWORD='password-reset',
    BLOC='bloc',
    SCHEDULER='scheduler',
}
